//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSistemaPesquisaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Alternativas
    {
        public int AlternativaId { get; set; }
        public int QuestaoId { get; set; }
        public string Alternativa { get; set; }
    
        public virtual TB_Questoes TB_Questoes { get; set; }
    }
}
